// Generated by CoffeeScript 1.7.1
"use strict";
var assert, helpers;

helpers = require('yeoman-generator').test;

assert = require('yeoman-generator').assert;

describe("Ajency theme module test", function() {
  var module;
  module = null;
  before(function() {
    return module = require("../module");
  });
  it("can be imported without blowing up", function() {
    return assert(module !== void 0);
  });
  return it("must run with 0 arguments", function() {
    module = helpers.createGenerator('module', ['module']);
    return module.run();
  });
});
