// Generated by CoffeeScript 1.7.1
"use strict";
var assert;

assert = require("assert");

describe("ajency-theme generator", function() {
  return it("can be imported without blowing up", function() {
    var app;
    app = require("../app");
    return assert(app !== 'undefined');
  });
});

//# sourceMappingURL=test-load.map
