language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'ajency-theme' ]; then cd .. && eval "mv $currentfolder ajency-theme"
   && cd ajency-theme; fi