language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-aj-theme' ]; then cd .. && eval "mv $currentfolder generator-aj-theme" && cd generator-aj-theme; fi

