// Generated by CoffeeScript 1.7.1
"use strict";
var ModuleGenerator, util, yeoman;

util = require("util");

yeoman = require("yeoman-generator");

ModuleGenerator = yeoman.generators.NamedBase.extend({
  init: function(args) {
    return console.log("You called the module subgenerator with the argument " + arguments[1]);
  }
});

module.exports = ModuleGenerator;
