// Generated by CoffeeScript 1.7.1
"use strict";
var ModuleGenerator, util, yeoman, _s;

util = require("util");

yeoman = require("yeoman-generator");

_s = require('underscore.string');

ModuleGenerator = yeoman.generators.Base.extend({
  init: function(args, name) {
    return this.pkg = require("../package.json");
  },
  askFor: function() {
    var cb, prompts;
    cb = this.async();
    prompts = [
      {
        name: "moduleName",
        message: "Name of the module you want to create?"
      }, {
        name: "templateAuthor",
        message: "Template author name( Format: name (email) )  "
      }
    ];
    return this.prompt(prompts, (function(_this) {
      return function(props) {
        _this.moduleName = props.moduleName, _this.templateAuthor = props.templateAuthor;
        _this.slugifiedModuleName = _s.slugify(_this.moduleName);
        return cb();
      };
    })(this));
  },
  createSPAModule: function() {
    var spawnCommand;
    this.template("module.spa.coffee", "" + this.slugifiedModuleName + ".spa.coffee");
    this.template("module.app.coffee", "pages/" + this.slugifiedModuleName + ".app.coffee");
    this.template("template-wp.php", "../template-" + this.slugifiedModuleName + ".php");
    this.template("module.styles.less", "../css/" + this.slugifiedModuleName + ".styles.less");
    spawnCommand = require('spawn-command');
    return spawnCommand("wp post create --post_type=page --post_status=publish --post_title='" + this.moduleName + "'");
  }
});

module.exports = ModuleGenerator;
